### ISSUE TITLE
Bug: Major: Firefox/Safari:  Humberger menu is not displayed for Subscribe to Bulldog block in firefox & other cosmetic issue in safari

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#273]
Steps:
1. Navigate to https://209-bulldog-modal--vg-macktrucks-com--hlxsites.hlx.page/magazine/ in desktop - Firefox 
2.  Repeat above step for Mobile - Firefox
3. Repeat step1 for desktop - safari browser

**Desktop & Mobile - Firefox:**
Humberger menu is not displayed in desktop/mobile viewports
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/c391bdac-70ad-4eec-9615-00404a4ea4c8">

**Desktop Safari:**
'Subscribe to Bulldog' is not displayed correctly 
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/55ce35fe-56f3-46c4-a18b-724c460e5a16)

**Comment by girishdigrajkar** [comment]
Retest Failed; Please investigate

**Comment by TomaszDziezykNetcentric** [comment]
Hi @girishdigrajkar 
The fix was merged to the main branch so you can test it on the:
https://main--vg-macktrucks-com--hlxsites.hlx.page/magazine/
or on the env created for this bug: 
https://273-hamburger-menu-fix--vg-macktrucks-com--hlxsites.hlx.page/

The fix wasn't merged into 209 so you can't test it on: https://209-bulldog-modal--vg-macktrucks-com--hlxsites.hlx.page/magazine/

**Comment by girishdigrajkar** [comment]
Partially Fixed: 
Humberger menu is displayed now on firefox:
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/154ab3c3-8acb-4586-8999-8c24b5cb2f31">

Safari issue related to 'Subscribe to Bulldog' button text is not fixed:
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/9f632845-6949-4af7-a5a2-adb8ae9b21f6">

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/b7d11f49-c8c9-4da1-9f10-862305a086e7">
