### ISSUE TITLE
Adjust the height of the iFrame of Contact Us form

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#564]
**Description**
For both the "Request a Quote" and "Contact Us" forms, when user clicks submit, there is a thank you message that appears. At the moment, this process doesn't appear to be as smooth as it could be. Since this ticket was first written, the Alchemer form was set up and is being used instead of the MCAE link in the iFrame block.

The goal is to be able to show a thank you message with the collapsable iFrame that adjusts to the one line in the thank you message.

**Acceptance criteria:**
That the iframe collapses after the user submits the form to the height of the one line in the Thank you message
That the thank you message looks like it fits within the styling of the site.

**Comment by CasiMcDaniel** [comment]
@KJohnsn Is this being worked in current sprint? There is a large need to have this functionality for our media pages/pages with forms. 

@jrcooke12 @WendyKruger @ZoeBeykirch

**Comment by BeckyMedlin** [comment]
@CasiMcDaniel This is not in the current sprint. We can discuss in our next prioritization meeting on 2/26 if it doesn't get added to sprint 3.

**Comment by amglebihan** [comment]
@KJohnsn @ZoeBeykirch I'd need some clarification regarding this spike. If I check the [Request a Quote](https://www.macktrucks.com/buy-mack/request-a-quote/) and [Contact us](https://www.macktrucks.com/about-mack/contact-us/contact-us-form/) forms, I see that there is currently a thank you message shown within the iframe after the forms are submitted. I get the part to adjust the height of the iframe when the thank you message is displayed, but I'd like to have more information regarding the redirect. For the Contact us form, we currently have this [page](https://www.macktrucks.com/about-mack/contact-us/thank-you/) configured, but I don't see it used. How do you want this redirect to be working? Is it an extra step on top of of the thank you message that we're currently showing? How should it be configured, displayed...?

**Comment by KJohnsn** [comment]
@amglebihan the forms are linked to Marketing Cloud Account Engagement in Salesforce which I will involve @ryanropero here in the comment so that we can talk through how the form connects to MCAE. The idea of the thank you message is for it to appear within the same space after the person has submitted the form instead of going to a separate thank you page. There is a Spike ticket raised in terms of finding a solution to manage Salesforce Web-to-case routing which we need Adobe to provide a solution for. Not sure about going to AEM when we are on EDS. Would rather keep the solutions within the EDS framework as much as possible.

**Comment by ryanropero** [comment]
@amglebihan So the iframe currently redirects to a new page that has the thank you text displayed instead of the iframe module. Ideally, we would like to not have to redirect to a new page.  The reason for the redirect is that the iframe modal height is locked to the height of the form and is not dynamic. So when the form is submitted it leaves a massive whitespace. It does not adjust the height. Does that make sense?

**Comment by amglebihan** [comment]
@ryanropero It does make sense, but I guess that I'm not checking the form on the right page then? This is the one I was looking at https://www.macktrucks.com/about-mack/contact-us/contact-us-form/
and there, the thank you message appears within the iframe and not in a new page that has the thank you text. Could you point me to the correct one? Thanks

**Comment by ryanropero** [comment]
@amglebihan that particular from is an Alchemer form and does not currently go into Salesforce.  This is dues to the routing rules based on submission data.  That is a temp solution as we would like to replace it with a Salesforce Web2Case

**Comment by amglebihan** [comment]
@KJohnsn @ryanropero After some investigation, as the iframes' content is served from a different origin, direct access to the content of the iframe is restricted. The safest way to go to detect when the forms are submitted would be to use [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to send a message from the iframe to the parent. That would allow me to know when the forms are submitted and trigger a function to change the iframes' height.

For Pardot, you can check this [page](https://help.walnut.io/hc/en-us/articles/23424098132755-Adding-Custom-JavaScript-to-Your-Pardot-Form) that has documentation (step 3). The code to be added would be this:
`<script type="text/javascript">
  window.parent.postMessage('requestAQuoteFormSubmitted', 'https://www.macktrucks.com');
</script>`

For Alchemer, you can check this [page](https://help.alchemer.com/help/adding-javascript-to-your-survey) that also has documentation. The code to be added would be this:
`document.addEventListener("DOMContentLoaded", function() {
    var form = document.getElementById('sg_FormFor7773660');
    if (form) {
      form.addEventListener('submit', function(event) {
        window.parent.postMessage('contactFormSubmitted', 'https://www.macktrucks.com');
      });
    }
  });`

Would that be a feasible solution?

**Comment by ryanropero** [comment]
@amglebihan I can add script to the form. Let me know the script you would like to add and what form to add it to, so we can test

**Comment by amglebihan** [comment]
@ryanropero you have the scripts in my message above. The first one is for the request a quote form and the second one for the contact us form. Please note that this will only work for https://www.macktrucks.com. If it needs to work on other markets please let me know. But for now we could test it only for https://www.macktrucks.com.

**Comment by ryanropero** [comment]
@amglebihan ok, he "request a quote" is done. Can you please test? 

@Joesturbo are you able to update the Alchemer form?

**Comment by amglebihan** [comment]
@ryanropero the message isn't received on my local instance. Can you please try with this instead and let me know when you've done the change? Thanks

```
<script type="text/javascript"> 
window.parent.postMessage('requestAQuoteFormSubmitted', '*');
</script>
```

**Comment by ryanropero** [comment]
I updated the script

Ryan Ropero
Senior Business Analyst – Salesforce/Account Engagement
​
Volvo Group Digital & IT
Volvo Group Digitla & IT | Commercial Solutions NA​
T. 904 495 3717
7900 National Service Rd | Greensboro, NC, 27409 | USA
***@***.******@***.***>
***@***.***

**Comment by amglebihan** [comment]
@ryanropero I'm still not receiving any message from the script upon form submission, so I updated it to have something similar to what I added for the contact us form. Hopefully it's fine now. Thanks.

```
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    var form = document.getElementById('pardot-form');
    form.addEventListener('submit', function() {
      window.parent.postMessage('requestAQuoteFormSubmitted', '*')
    });
  });
</script>
```

**Comment by ryanropero** [comment]
OK updated with new code.


Ryan Ropero
Senior Business Analyst – Salesforce/Account Engagement
​
Volvo Group Digital & IT
Volvo Group Digitla & IT | Commercial Solutions NA​
T. 904 495 3717
7900 National Service Rd | Greensboro, NC, 27409 | USA
***@***.******@***.***>
***@***.***

**Comment by KJohnsn** [comment]
@amglebihan @Joesturbo - from our call on 5/3, Joe tried adding in the scripts but there is a bit more complexity to the Alchemer form than we thought. Also, if we could provide Alan direct access to Alchemer, then there is a possibility he can trouble shoot a bit better and be able to work on and possibly resolve the issue with the collapsed iFrame after the user clicks the back button after submitting the form in the browser. More follow up is needed.

**Comment by amglebihan** [comment]
@KJohnsn @Joesturbo @ryanropero

To summarise our current status with the forms and the various solutions available:
* We have implemented a script in both Pardot and Alchemer that triggers a message upon form submission. This message can be captured by an event listener to adjust the iframe’s height. However:
    * This message is dispatched regardless of whether the form is submitted successfully or with validation errors, causing the iframe’s height to adjust in both scenarios. I believe this does not enhance the user experience, as changing the frame’s height during validation errors is not ideal. I have not found documentation or a method that allows the message to be sent exclusively on successful submissions. Furthermore, each platform employs its own validation system. There may be a solution within Pardot or Alchemer, but I currently lack access to verify this.
    * Upon successful submission, a thank-you message is displayed. If the user then presses the browser’s back button, there isn’t a reliable method to detect this action. Currently, the iframe’s height doesn’t go back to its initial height after the back button is clicked. Access to both platforms would be necessary to explore possible solutions.
* I tried using a modal for the contact us form, but it does not currently support iframes, or would require additional styling. Additionally, this approach is not suitable for the request a quote form.
* I also reviewed the [contact us form](https://www.partsasist.com/#contact) on partsasist as a potential solution; however, it would require new designs and styling for the form elements. Also, considering the spike detailed at https://github.com/hlxsites/vg-volvotrucks-us/issues/603, it may not be prudent to implement anything similar to partsasist if we might plan to build the forms another way in the future.

**Comment by KJohnsn** [comment]
Based on your input @amglebihan we really need to see whether we do continue down this route, or if we simply park it for now. It may be best to park it. After we see what the outcome is for the EDS block spike, then we can determine if this is still needed.

**Comment by amglebihan** [comment]
@KJohnsn It sounds good. I was thinking the same.

**Comment by BeckyMedlin** [comment]
Removed from sprint. Will review to determine if this is still needed after https://github.com/hlxsites/vg-volvotrucks-us/issues/603 is completed. @KJohnsn @amglebihan @mollyaljenkins @verareljic

**Comment by ZoeBeykirch** [comment]
@ryanropero @KJohnsn please confirm if this ticket is still needed. Should we instead plan to use MCAE forms instead of Alchmer forms for the contact us and request a quote?

**Comment by KJohnsn** [comment]
@ZoeBeykirch we are not quite ready yet to move from Alchemer to MCAE. This is currently in process and in testing. We will need to keep this ticket for the time being.

**Comment by ZoeBeykirch** [comment]
Confirmed with Ken and Wendy that we can close this ticket as we are planning to move away from Alchmer forms in the near future.
